### ISSUE TITLE
Broken files

### ISSUE THREAD

**Issue by azzaea** [adimitromanolakis/truffle#2]
Hi!

Kindly note that the vcf files uploaded as `dataset A` and `dataset B` from the manuscript are broken/ malformatted.  Would be great if you could upload them/ or modify the README.

Best,
Azza

**Comment by adimitromanolakis** [comment]
Hi, can you try downloading the files through the github website? For example try:
https://github.com/adimitromanolakis/truffle/blob/master/datasets/vcf-ld01-thin-mod.vcf.gz

Because the files are stored in GitLFS storage, they might not download correctly if you do a git clone or otherwise clone the repository.

Let me know if this works,

Apostolos

**Comment by azzaea** [comment]
Nice! 
Thank you very much. I didn't know about GitLFS before, but once it is installed, I could git clone the repo as usual, and the files are working fine now.

Probably worth mentioning in the README?

Thank you again,
Azza

**Comment by azzaea** [comment]
Closing, since the README is now updated
